version: '3'
services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    user: root
    networks:
      - kind

  # agent:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.agent
  #   privileged: true
  #   user: root
  #   container_name: agent
  #   expose:
  #     - 22
  #   environment:
  #     - JENKINS_AGENT_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDPvHpq4JIAlQFxaXISmeD/xG6YMeDQ3hvC7/itsg3XHfABYuf1E6MHvGo2SEmr0IB90XaDnEH5XaJBH5bpolv2ik6gqAcgFutNuSPg7d+zSYEewLJ6f+hw5dI0w0NJo5avcf2r7B1obUP9wshFLe7tvK10JweXfzqdxVYA6fcbDyYDbOC+/alNezPk7368vo0gLVCZxwy6zjZjoIw9b89s2/YFe9IfHB7C+KwxMZtp44nNq14YnLOhYLuhv55kC7KhuXcEYcEbeA9xhx/4G48LKXc1tTWzjQKpy5GtDtizJA+VuWHYYFE5R9nOegoY9pQAk90s8kfp4/ZvMXOfibl/xNLzTZHucyEb6ssW5ELaOi6XdZZxzz1st8nlKA0AQzDsu3oDmN9alprUQa16tpZn4dzRllCDqmQVZCaBGF65cN21eP7kC1QMMbvQ8txnKbzqEVt3R/5wTA7Txt18BdYdLAa9krYqr917RdA3QNeI/YhCEvDMYnyuek2UGUIK5OM= lakshminp@lakshminp

networks:
  kind: # define the kind network
    external: true #
