version: '3'
services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "51000:50000"
    networks:
      - mynetwork
    volumes:
      - ./jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    user: root

  gitea:
    image: gitea/gitea:1.12.4
    volumes:
      - ./data:/data
    ports:
      - "3100:3000"  # Change the host port from "3000" to "3100" (or any other desired port)
      - "2222:22"
    depends_on:
      - db
    restart: always
    networks:
      - mynetwork

  db:
    image: mariadb:10
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=changeme
      - MYSQL_DATABASE=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=changeme
    volumes:
      - ./db/:/var/lib/mysql
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
